### PR TITLE
Restructure CI

### LINKED ISSUE #8: How about restructuring CI?
- [x] Run unit tests on PHP 7.1 - nighly

- [x] Upload results to scrutinizer only once https://scrutinizer-ci.com/g/voku/Simple-PHP-Code-Parser/ (not enabled?)
- [x] Upload results to codecov only once https://codecov.io/github/voku/Simple-PHP-Code-Parser
- [x] Run static analysis once in a separate job: phpstan and psalm
- [x] Run PhpCsFixer
- [ ] Enable Scrutinizer?
- [ ] Enable StyleCI
- [x] Test run `box`
- [ ] Enable CircleCI https://app.circleci.com/pipelines/github/voku/Simple-PHP-Code-Parser
- [ ] and add badges

What do you think?

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes #8

### CODE REVIEW

**Comment by szepeviktor** [comment]
@voku Please clear Travis caches to allow usage of older phive on PHP 7.1
https://travis-ci.com/github/voku/Simple-PHP-Code-Parser

**Comment by voku** [comment]
Cache is cleared.

**Comment by szepeviktor** [comment]
Fixed Travis warnings

kép

**Comment by szepeviktor** [comment]
All green 🍏 

psalm complains: https://travis-ci.com/github/voku/Simple-PHP-Code-Parser/jobs/362416392#L347

**Comment by szepeviktor** [comment]
PHPStan is also preferred to be installed with phive.

```xml
  <phar name="phpdocumentor" version="2.9.1" installed="2.9.1" location="./tools/phpDocumentor" copy="false"/>
  <phar name="phpstan" version="^0.12.32" installed="0.12.32" location="./tools/phpstan" copy="false"/>
```

GPG key: CF1A108D0E7AE720

**Pull request merged**
